CI: invalidate cache and enable scheduled job
xapi-project/xenopsd pull request #763
Opened 2021-07-13 08:22 UTC by edwintorok

2021-07-13 09:05 UTC, psafont approved these changes

2021-07-13 09:06 UTC, psafont requested changes
Scheduled jobs confusingly only run from the master branch, please don't enable it here: https://github.com/xapi-project/xenopsd/blob/master/.github/workflows/0.150-lcm.yml

2021-07-13 13:52 UTC, lindig approved these changes

2021-07-13 13:52 UTC, lindig commented on .github/workflows/0.150-lcm.yml
> +    - cron: '13 2 * * 1'
Might want to add a reminder about the fields in cron:
```
# m h  dom mon dow `
```

2021-07-26 09:18 UTC, psafont commented
This has been fixed with https://github.com/xapi-project/xenopsd/pull/765

2021-07-26 09:18 UTC, closed without merging